#!/bin/bash

# Generate test token for performance testing
# This script helps you get a JWT token for performance testing

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== Test Token Generator ===${NC}"
echo ""

# Check if auth server is running
AUTH_SERVER_URL=${AUTH_SERVER_URL:-"http://localhost:8081"}
if ! curl -s -f "$AUTH_SERVER_URL/health" > /dev/null 2>&1; then
    echo -e "${YELLOW}Warning: Auth server at $AUTH_SERVER_URL may not be running${NC}"
    echo "Make sure the auth server is started before running this script."
    echo ""
fi

echo "This script will attempt to get a token using client_credentials grant"
echo "with the following test credentials:"
echo "  Client ID: test-client"
echo "  Client Secret: test-secret-key"
echo ""

# Test client credentials (hardcoded for performance testing)
CLIENT_ID="test-client"
CLIENT_SECRET="test-secret-key"

echo -e "${YELLOW}Attempting to get token via client_credentials grant...${NC}"
echo "  Client ID: $CLIENT_ID"
echo "  Auth Server: $AUTH_SERVER_URL"
echo ""

# Try to get token via client_credentials grant
RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$AUTH_SERVER_URL/oauth2/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "$CLIENT_ID:$CLIENT_SECRET" \
  -d "grant_type=client_credentials" \
  -d "scope=read write" 2>&1) || true

# Extract HTTP code and body (macOS compatible)
HTTP_CODE=$(echo "$RESPONSE" | tail -n 1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "200" ] && echo "$BODY" | grep -q "access_token"; then
    TOKEN=$(echo "$BODY" | grep -o '"access_token":"[^"]*' | cut -d'"' -f4)
    if [ -n "$TOKEN" ]; then
        echo -e "${GREEN}✓ Successfully obtained token via client_credentials grant${NC}"
        echo ""
        echo "Token: $TOKEN"
        echo ""
        echo "To use this token, set it in your environment:"
        echo "  export TOKEN=\"$TOKEN\""
        echo ""
        echo "Or add it to .env.perf-test:"
        echo "  TOKEN=$TOKEN"
        echo ""
        echo "You can now run performance tests:"
        echo "  ./scripts/run-performance-test.sh"
        echo ""
        
        # Optionally save to .env.perf-test if it doesn't exist
        if [ ! -f "$PROJECT_ROOT/.env.perf-test" ]; then
            echo -e "${YELLOW}Creating .env.perf-test file...${NC}"
            cat > "$PROJECT_ROOT/.env.perf-test" << EOF
# Performance Test Environment Variables
# Generated by generate-test-token.sh

TOKEN=$TOKEN
CHANNEL_ID=1
CONNECTIONS=10
DURATION=60
MESSAGES_PER_SEC=1
EOF
            echo -e "${GREEN}Created .env.perf-test file${NC}"
        else
            echo -e "${YELLOW}Note: .env.perf-test already exists. Update it manually if needed.${NC}"
        fi
    else
        echo -e "${RED}✗ Failed to extract token from response${NC}"
        echo "Response: $BODY"
    fi
else
    echo -e "${RED}✗ Failed to get token (HTTP $HTTP_CODE)${NC}"
    echo "Response: $BODY"
    echo ""
    echo -e "${YELLOW}Alternative: Get token from browser${NC}"
    echo "  1. Start the application: ./start-all.sh"
    echo "  2. Log in at http://localhost:3000"
    echo "  3. Open DevTools → Application → Local Storage"
    echo "  4. Copy the 'slack_auth_token' value"
    echo ""
    echo "Then set it as environment variable:"
    echo "  export TOKEN=\"your_token_here\""
    echo ""
fi

